CREATE DATABASE MySQLDB_special2;
USE MySQLDB_special2;
CREATE TABLE STUDENT (
	StudentSSN INT NOT NULL DEFAULT 55,
	StudentName DOUBLE DEFAULT 5.0,
CONSTRAINT STUDENT_PK PRIMARY KEY (StudentSSN)
);

CREATE TABLE FACULTY (
	FacultyName VARCHAR(100) DEFAULT "Bob",
	FacSSN VARCHAR(1),
CONSTRAINT FACULTY_PK PRIMARY KEY (FacultyName)
);

CREATE TABLE COURSES (
	Grade BOOL NOT NULL,
	Number DOUBLE NOT NULL DEFAULT 2.0,
);


